version: "3"
services:
  hive-soaring-sparrow-android:
    build:
      context: .
      dockerfile: Dockerfile.android
      target: dev
    volumes:
      - $PWD/src:/usr/src/app/src
      - $PWD/android:/usr/src/app/android
      - $PWD/assets:/usr/src/app/assets
      - $PWD/scripts:/usr/src/app/scripts
      - $PWD/.git:/usr/src/app/.git
      - $PWD/packager:/usr/src/app/packager
      - $PWD/patches:/usr/src/app/patches
      - $PWD/package.json:/usr/src/app/package.json.tmp
      - $PWD/yarn.lock:/usr/src/app/yarn.lock.tmp
      - $PWD/index.android.js:/usr/src/app/index.android.js
      - $PWD/babel.config.js:/usr/src/app/babel.config.js
      - $PWD/app.json:/usr/src/app/app.json
      - $PWD/metro.config.js:/usr/src/app/metro.config.js
      - $PWD/jsconfig.json:/usr/src/app/jsconfig.json
      - $PWD/.svgrrc:/usr/src/app/.svgrrc
      - $PWD/.gradle-tmp:/root/.gradle
      - $PWD/react-native.config.js:/usr/src/app/react-native.config.js
    stdin_open: true
    tty: true
    deploy:
      resources:
        limits:
          cpus: "10"
          memory: "14g"
    cap_add:
      - NET_ADMIN
